# Thư viện 

In [1]:
from Mylib import myfuncs, stringToObjectConverter

In [2]:
models_yaml = myfuncs.read_yaml("demo.yaml")
models_yaml = models_yaml.models

models_yaml

models = [stringToObjectConverter.convert_MLmodel_yaml_to_object(model) for model in models_yaml]

models[0]


yaml file: demo.yaml loaded successfully


CustomStackingClassifier(estimators=[LogisticRegression(C=0.1),
                                     GaussianNB(var_smoothing=1e-08),
                                     SGDClassifier(alpha=10, loss='log_loss')],
                         final_estimator=LogisticRegression(C=0.1),
                         weights=BoxList([1, 2, 3]))

In [1]:
from Mylib import myfuncs 
import pandas as pd

a = pd.Series(['a', 'b', 'c', 'd', 'b', 'c', 'd'])

replace_value_list = [
    [['a', 'b'], 'ab'],
    [['c'], 'c1'],
]

a = myfuncs.replace_in_category_series_33(a, replace_value_list)

a

0    ab
1    ab
2    c1
3     d
4    ab
5    c1
6     d
dtype: category
Categories (3, string): [ab, c1, d]

In [ ]:
estimators = [[Logic, XGB, RandomForest], [Logic, XGB]]
final_estimator = RandomForest


In [4]:
list(models[0].weights)

[1, 2, 3]

In [13]:
import numpy as np 

a = np.asarray([[1,2], [2,3]])
b = np.asarray([[3,4], [4,5]])
c = np.asarray([[3,4], [4,5]])

c = [a,b, c]

np.hstack(c)

array([[1, 2, 3, 4, 3, 4],
       [2, 3, 4, 5, 4, 5]])

In [6]:
obj =  ast.literal_eval("[1,2]")
obj

[1, 2]

In [9]:
import os

path = os.path.join("artifacts", "hello.pkl")
filename = os.path.splitext(os.path.basename(path))[0]
filename

'hello'

In [1]:
from Mylib import stringToObjectConverter, myfuncs


models = myfuncs.read_yaml("demo.yaml").models

model = models[0]

print(myfuncs.get_model_desc_for_CustomStackingClassifier(model))



yaml file: demo.yaml loaded successfully
class_name: CustomStackingClassifier
estimators:
   - LogisticRegression(C = 0.1)
   - GaussianNB(var_smoothing=1e-8)
   - SGDClassifier(alpha=10, loss='log_loss')
final_estimator: LogisticRegression(C = 0.1)


In [ ]:
import numpy as np
from xgboost import XGBClassifier
from sklearn.datasets import make_classification
from sklearn import metrics

# Giả sử bạn có một tập dữ liệu với 10,000 dòng
X, y = make_classification(n_samples=10000, n_features=20, random_state=42)

# Khởi tạo XGBClassifier
model = XGBClassifier(n_estimators=5, learning_rate=0.1)

batch_size = 500

list_X_batch = [
    X[i : i + batch_size, :]
    for i in range(0, len(X), batch_size)
]

list_y_batch = [
    y[i : i + batch_size]
    for i in range(0, len(X), batch_size)
]

# Lặp qua từng batch, huấn luyện mô hình
for i, (X_batch, y_batch) in enumerate(zip(list_X_batch, list_y_batch)):
    if i == 0:
        # Huấn luyện lần đầu tiên
        model.fit(X_batch, y_batch)
    else:
        # Tiếp tục huấn luyện từ mô hình đã huấn luyện trước đó
        model.fit(X_batch, y_batch, xgb_model=model.get_booster())

# Dự đoán và đánh giá mô hình
y_pred = model.predict(X)
accuracy = metrics.accuracy_score(y, y_pred)
print(f"Accuracy: {accuracy}")


TypeError: fit() got an unexpected keyword argument 'hello'

In [39]:
model = XGBClassifier()

isinstance(model, XGBClassifier)

True

In [36]:
import re

text = "MLPClassifier(   warm_start   = True   ,hidden_layer_sizes=(64,32,16), activation='relu', max_iter=100, batch_size=1024, validation_fraction=0.1, early_stopping=True)"

# Tách tên lớp và tham số
class_name = text.split("(", 1)[0]

object_class = globals()[class_name]

format = r"\w+\s*=\s*[\w\(\),\']+"
param = re.findall(format, text)

param

# param_name = [item.split("=")[0].strip() for item in param]
# param_value = [item.split("=")[1].strip() for item in param]

# param_value

['warm_start   = True',
 'hidden_layer_sizes=(64,32,16),',
 "activation='relu',",
 'max_iter=100,',
 'batch_size=1024,',
 'validation_fraction=0',
 'early_stopping=True)']

In [16]:
model = MLPClassifier(warm_start=True)

In [9]:
import xgboost 

print(xgboost.__version__)

2.1.4


In [ ]:
batch_size = 500
list_X_batch = [
X[i : i + batch_size, :]
for i in range(0, len(X), batch_size)
]

list_y_batch = [
y[i : i + batch_size]
for i in range(0, len(X), batch_size)
]

for X_batch, y_batch in zip(list_X_batch, list_y_batch) : 
    model.fit(X_batch, y_batch)

0         1         2         3         4         5         6  \
0    -0.097248 -0.043218 -0.265815  0.111935  0.150092 -0.016558  0.017185   
1     0.186874 -0.134880 -0.117323 -0.049524  0.111066 -0.218406  0.167135   
2     0.155977 -0.006309 -0.017333  0.201616  0.098383  0.190598  0.078926   
3    -0.312429 -0.111052 -0.050050  0.080957  0.201140  0.092766 -0.114738   
4     0.031333  0.097333 -0.057367 -0.030342  0.154183 -0.073601 -0.153181   
...        ...       ...       ...       ...       ...       ...       ...   
9995  0.395789 -0.092389 -0.003644  0.152082 -0.080188  0.011601 -0.082576   
9996  0.204065 -0.246415  0.214963  0.215878  0.085831  0.234779  0.058144   
9997 -0.370814 -0.001821 -0.037114  0.213185 -0.205793  0.033708  0.150469   
9998  0.237864 -0.085875 -0.226185  0.087428 -0.042542 -0.010563 -0.006005   
9999  0.129645  0.234303 -0.030473 -0.182321  0.194892  0.094931  0.221302   

             7         8         9  
0     0.103372  0.049894 -0.184696  
1    -0.051754 -0.007685 -0.035729  
2    -0.165511 -0.166385  0.136122  
3    -0.086712  0.042215 -0.099011  
4    -0.064510  0.062237  0.016441  
...        ...       ...       ...  
9995 -0.090687 -0.218288 -0.054186  
9996  0.079624  0.099719 -0.057190  
9997  0.023313  0.060360  0.276384  
9998 -0.053812  0.141612 -0.199983  
9999  0.173041 -0.129665  0.212641  

[10000 rows x 10 columns]

In [13]:
y

array([1, 1, 1, ..., 0, 1, 1])

In [15]:
# Chia dữ liệu thành 6 batch, mỗi batch có 50,000 dòng
batch_size = 500
num_batches = X.shape[0] // batch_size

# Khởi tạo KernelPCA với kernel là 'rbf' (Radial Basis Function)
kpca = KernelPCA(kernel='rbf', n_components=10)

# Tính toán ma trận hạt nhân cho toàn bộ dữ liệu sau khi fit trên các batch
# Không thực hiện transform ở đây, chỉ lưu các thông tin cần thiết
for i in range(num_batches):
    print(f"Fit batch no. {i}")
    start = i * batch_size
    end = (i + 1) * batch_size
    batch = X[start:end]

    # Fit KernelPCA cho batch hiện tại
    kpca.fit(batch)
    
# Sau khi fit tất cả các batch, transform toàn bộ dữ liệu
print("Tiến hành transform dữ liệu")
X_transformed = kpca.transform(X)

# Bây giờ, bạn có thể sử dụng X_transformed cho các tác vụ khác như phân loại, phân cụm,...
print(X_transformed.shape)

Fit batch no. 0
Fit batch no. 1
Fit batch no. 2
Fit batch no. 3
Fit batch no. 4
Fit batch no. 5
Fit batch no. 6
Fit batch no. 7
Fit batch no. 8
Fit batch no. 9
Fit batch no. 10
Fit batch no. 11
Fit batch no. 12
Fit batch no. 13
Fit batch no. 14
Fit batch no. 15
Fit batch no. 16
Fit batch no. 17
Fit batch no. 18
Fit batch no. 19
Tiến hành transform dữ liệu
(10000, 10)


In [10]:
X_transformed

array([[ 0.06832064,  0.1522096 ],
       [ 0.18322921,  0.02435615],
       [ 0.03261752,  0.05863166],
       ...,
       [ 0.15806078,  0.23795613],
       [-0.33751886,  0.00462025],
       [-0.42269551, -0.19284862]])

In [ ]:
def do_ast_literal_eval_advanced_7(text: str):
    """Kế thừa hàm ast.literal_eval() nhưng xử lí thêm trường hợp sau

    Tuple, List dạng (1.0 ; 2.0), các phần tử cách nhau bởi dấu ; thay vì dấu ,

    """
    if ";" not in text:
        return ast.literal_eval(text)

    return ast.literal_eval(text.replace(";", ","))


def convert_complex_string_to_object_4(text: str):
    """Chuyển 1 chuỗi thành 1 đối tượng

    Example:
        text = "LogisticRegression(C=144, penalty=l1, solver=saga ,max_iter=10000,dual=True)"

        -> đối tượng LogisticRegression(C=144, dual=True, max_iter=10000, penalty='l1',solver='saga')

    Args:
        text (str): _description_


    """
    # Tách tên lớp và tham số
    class_name, params = text.split("(", 1)
    params = params[:-1]

    object_class = globals()[class_name]

    if params == "":
        return object_class()

    # Lấy tham số của đối tượng
    param_parts = params.split(",")
    param_parts = [item.strip() for item in param_parts]
    keys = [item.split("=")[0].strip() for item in param_parts]

    values = [
        do_ast_literal_eval_advanced_7(item.strip().split("=")[1].strip())
        for item in param_parts
    ]

    params = dict(zip(keys, values))

    return object_class(**params)

